/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArtisanRouteImport } from './routes/artisan'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as LuxuryRouteImport } from './routes/luxury'
import { Route as OrderRouteImport } from './routes/order'
import { Route as TrackRouteImport } from './routes/track'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as CountriesCodeRouteImport } from './routes/countries.$code'
import { Route as PortalsArtisanRouteImport } from './routes/portals.artisan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanRoute = ArtisanRouteImport.update({
  id: '/artisan',
  path: '/artisan',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryRoute = LuxuryRouteImport.update({
  id: '/luxury',
  path: '/luxury',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCodeRoute = CountriesCodeRouteImport.update({
  id: '/countries/$code',
  path: '/countries/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsArtisanRoute = PortalsArtisanRouteImport.update({
  id: '/portals/artisan',
  path: '/portals/artisan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/artisan': typeof ArtisanRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRoute
  '/luxury': typeof LuxuryRoute
  '/order': typeof OrderRoute
  '/track': typeof TrackRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/portals/artisan': typeof PortalsArtisanRoute
  '/countries/': typeof CountriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/artisan': typeof ArtisanRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRoute
  '/luxury': typeof LuxuryRoute
  '/order': typeof OrderRoute
  '/track': typeof TrackRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/portals/artisan': typeof PortalsArtisanRoute
  '/countries': typeof CountriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/artisan': typeof ArtisanRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRoute
  '/luxury': typeof LuxuryRoute
  '/order': typeof OrderRoute
  '/track': typeof TrackRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/portals/artisan': typeof PortalsArtisanRoute
  '/countries/': typeof CountriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/artisan'
    | '/collections'
    | '/contact'
    | '/gallery'
    | '/heritage'
    | '/luxury'
    | '/order'
    | '/track'
    | '/countries/$code'
    | '/portals/artisan'
    | '/countries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/artisan'
    | '/collections'
    | '/contact'
    | '/gallery'
    | '/heritage'
    | '/luxury'
    | '/order'
    | '/track'
    | '/countries/$code'
    | '/portals/artisan'
    | '/countries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/artisan'
    | '/collections'
    | '/contact'
    | '/gallery'
    | '/heritage'
    | '/luxury'
    | '/order'
    | '/track'
    | '/countries/$code'
    | '/portals/artisan'
    | '/countries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ArtisanRoute: typeof ArtisanRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HeritageRoute: typeof HeritageRoute
  LuxuryRoute: typeof LuxuryRoute
  OrderRoute: typeof OrderRoute
  TrackRoute: typeof TrackRoute
  CountriesCodeRoute: typeof CountriesCodeRoute
  PortalsArtisanRoute: typeof PortalsArtisanRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan': {
      id: '/artisan'
      path: '/artisan'
      fullPath: '/artisan'
      preLoaderRoute: typeof ArtisanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury': {
      id: '/luxury'
      path: '/luxury'
      fullPath: '/luxury'
      preLoaderRoute: typeof LuxuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$code': {
      id: '/countries/$code'
      path: '/countries/$code'
      fullPath: '/countries/$code'
      preLoaderRoute: typeof CountriesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals/artisan': {
      id: '/portals/artisan'
      path: '/portals/artisan'
      fullPath: '/portals/artisan'
      preLoaderRoute: typeof PortalsArtisanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ArtisanRoute: ArtisanRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HeritageRoute: HeritageRoute,
  LuxuryRoute: LuxuryRoute,
  OrderRoute: OrderRoute,
  TrackRoute: TrackRoute,
  CountriesCodeRoute: CountriesCodeRoute,
  PortalsArtisanRoute: PortalsArtisanRoute,
  CountriesIndexRoute: CountriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
